services:
    frontend:
        image: whitesf-frontend
        ports:
            - '3001:80'

    backend:
        image: whitesf-backend
        environment:
            LOG_LEVEL: 'debug'
            LOG_PATH: '/home/node/app/backend/logs'
            GAME_MIN_PLAYERS: '3'
            GAME_TICK_INTERVAL_MS: '3000'
            GAME_VOTING_TIME_MS: '15000'
            SERVER_PORT: '3000'
            SERVER_BASE_PATH: 'localhost'
            FRONTEND_URL: 'http://frontend:80'

        ports:
            - '3000:3000'
